### ISSUE TITLE
Large playlist causes frequent freezing

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#129]
Prior to and at the end of each playlist track, jub freezes for 10-25 seconds. During the freeze, the audio continues, but all site interactivity is locked - cannot chat and nothing changes visually.

This seems to be related to having a very large playlist; the playlist in use when this was encountered contains over 550 tracks.

Does not affect other jubs in the site, localized to client user.

**Comment by aromatt** [comment]
My guess is that the expensive part is repopulating the queue in the UI.  We should do something more lightweight than just sending back the entire updated playlist from the server whenever a video plays.  Maybe have the client be responsible for updating the playlist, and sending it to the server, or have the server send some message like "take top track from your queue" and the client can just remove that top <li> instead of redrawing the whole list.

**Comment by aromatt** [comment]
Turns out it is mostly the "truncate" part of drawing each video title in the UI.  We can get around this by using a Gmail-style table, and not truncating at all... just hiding the end of the title behind the next table cell.  Copied from a Gmail row:
```html
<td id=":7r" tabindex="-1" class="xY a4W">
  <div class="xS" role="link">
    <div class="xT">
      <div class="y6">
        <span id=":7t"><b>Projects We Love: Ripple Effect</b></span>
        <span class="y2">&nbsp;-&nbsp;This week in Kickstarter When Sundance announced their official selections this week, we were</span>
      </div>
    </div>
  </div>
</td>
```
The td has css `overflow: visible; white-space: nowrap;` and all the elements inside it have `overflow: hidden; white-space: nowrap;`
