### ISSUE TITLE
Remove DJ from rotation automatically if that person leaves the website

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#166]
Currently, it seems as though if someone is DJing, then leaves the pub without un-DJing, their playlist will continue to play infinitely (as it repeats), and those of us in the pub have no way to stop it.

There could be value in developing a system that does allow jubs to continue DJing once they leave, as long as anyone in the pub can then kick them out of the DJ rotation manually.

**Comment by aromatt** [comment]
Good idea.  So...

Currently you can already skip a DJ's track if the DJ has left the DJ rotation but their video is still playing.  
Some potential additional rules:
 - if someone leaves the room but left themselves in the DJ rotation, anyone can skip their tracks.
 - to build on the above... make it so that skipping someone who has left the room also kicks them off the DJ chair.

This would be a stepping stone on the way to more sophisticated room controls.

**Comment by aromatt** [comment]
After considering these options for a while, I think for now I will just do the simplest thing: remove the person from the DJ rotation if they leave the room.
