### ISSUE TITLE
Ideas for alternate top/bottom bar UI

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#174]
![jubpub](https://cloud.githubusercontent.com/assets/14909827/12851738/78ab4d3c-cbf9-11e5-967c-54a30ec65242.jpg)

**Comment by aromatt** [comment]
(from chat):

The reason I put the DJ name and track at the bottom is because that's how other audio-playing sites/apps do it, like google music, soundcloud, spotify, plug, etc
it seems to be a standard so I wanted to do the least surprising thing 
they also put audio controls down there... so I was considering moving hoot and skip down to the bottom too (a la plug)

The top bar, I was planning to leave for more administrative controls, like changing which room you're in, general settings, account, etc.  -- this seems to be a broader web standard

Video search will probably be worked into the queue menu, the way plug had it.  but it does look good on the bottom left jeskaeli, very symmetrical

**Comment by aromatt** [comment]
The current UI now looks like the suggested mock up, with a couple of changes.
